# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bai13/bai13.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13 || ORIG_REF_NAME==bai13} -quiet] -quiet

# IP: bd/bai13/ip/bai13_mig_7series_0_0/bai13_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_mig_7series_0_0 || ORIG_REF_NAME==bai13_mig_7series_0_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_clk_wiz_0_0/bai13_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_clk_wiz_0_0 || ORIG_REF_NAME==bai13_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_microblaze_0_0/bai13_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_microblaze_0_0 || ORIG_REF_NAME==bai13_microblaze_0_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_dlmb_v10_0/bai13_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_dlmb_v10_0 || ORIG_REF_NAME==bai13_dlmb_v10_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_ilmb_v10_0/bai13_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_ilmb_v10_0 || ORIG_REF_NAME==bai13_ilmb_v10_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_dlmb_bram_if_cntlr_0/bai13_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bai13_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_ilmb_bram_if_cntlr_0/bai13_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bai13_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_lmb_bram_0/bai13_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_lmb_bram_0 || ORIG_REF_NAME==bai13_lmb_bram_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_mdm_1_0/bai13_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_mdm_1_0 || ORIG_REF_NAME==bai13_mdm_1_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_rst_mig_7series_0_83M_0/bai13_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==bai13_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_axi_smc_0/bai13_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_axi_smc_0 || ORIG_REF_NAME==bai13_axi_smc_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_axi_gpio_0_0 || ORIG_REF_NAME==bai13_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bai13/ip/bai13_axi_uartlite_0_0/bai13_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai13_axi_uartlite_0_0 || ORIG_REF_NAME==bai13_axi_uartlite_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/bai13_ooc.xdc
