# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/btn_1.xdc

# Block Designs: bd/BTN_1/BTN_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1 || ORIG_REF_NAME==BTN_1} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_clk_wiz_0_0/BTN_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_clk_wiz_0_0 || ORIG_REF_NAME==BTN_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_mig_7series_0_0/BTN_1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_mig_7series_0_0 || ORIG_REF_NAME==BTN_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_microblaze_0_0/BTN_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_microblaze_0_0 || ORIG_REF_NAME==BTN_1_microblaze_0_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_dlmb_v10_0/BTN_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_dlmb_v10_0 || ORIG_REF_NAME==BTN_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_ilmb_v10_0/BTN_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_ilmb_v10_0 || ORIG_REF_NAME==BTN_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_dlmb_bram_if_cntlr_0/BTN_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BTN_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_ilmb_bram_if_cntlr_0/BTN_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BTN_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_lmb_bram_0/BTN_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_lmb_bram_0 || ORIG_REF_NAME==BTN_1_lmb_bram_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_mdm_1_0/BTN_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_mdm_1_0 || ORIG_REF_NAME==BTN_1_mdm_1_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_rst_mig_7series_0_83M_0/BTN_1_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==BTN_1_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_axi_smc_0/BTN_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_axi_smc_0 || ORIG_REF_NAME==BTN_1_axi_smc_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_axi_uartlite_0_0/BTN_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_axi_uartlite_0_0 || ORIG_REF_NAME==BTN_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BTN_1/ip/BTN_1_axi_gpio_0_0/BTN_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_1_axi_gpio_0_0 || ORIG_REF_NAME==BTN_1_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Buoi5_bai2/Buoi5_bai2.gen/sources_1/bd/BTN_1/BTN_1_ooc.xdc
