# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.srcs/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/BAI1_4LED_axi_smc_0.xci
# IP: The module: 'BAI1_4LED_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/bd_0a27.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_0/bd_0a27_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_2/bd_0a27_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_3/bd_0a27_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_4/bd_0a27_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_5/bd_0a27_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_6/bd_0a27_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_7/bd_0a27_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_8/bd_0a27_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_9/bd_0a27_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_10/bd_0a27_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_11/bd_0a27_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_12/bd_0a27_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_13/bd_0a27_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_14/bd_0a27_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_15/bd_0a27_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_16/bd_0a27_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_17/bd_0a27_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_18/bd_0a27_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_19/bd_0a27_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_20/bd_0a27_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_21/bd_0a27_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_22/bd_0a27_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_23/bd_0a27_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_24/bd_0a27_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_25/bd_0a27_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_26/bd_0a27_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_27/bd_0a27_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_28/bd_0a27_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_29/bd_0a27_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_30/bd_0a27_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_31/bd_0a27_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_32/bd_0a27_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_33/bd_0a27_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_34/bd_0a27_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_35/bd_0a27_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_36/bd_0a27_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_37/bd_0a27_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_38/bd_0a27_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_39/bd_0a27_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_40/bd_0a27_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_41/bd_0a27_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_42/bd_0a27_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_43/bd_0a27_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_44/bd_0a27_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_45/bd_0a27_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_46/bd_0a27_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_47/bd_0a27_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_48/bd_0a27_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_49/bd_0a27_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_50/bd_0a27_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_51/bd_0a27_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_2/bd_0a27_arsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_3/bd_0a27_rsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_4/bd_0a27_awsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_5/bd_0a27_wsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_6/bd_0a27_bsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_10/bd_0a27_s00a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_11/bd_0a27_sarn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_12/bd_0a27_srn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_13/bd_0a27_sawn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_14/bd_0a27_swn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_15/bd_0a27_sbn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_19/bd_0a27_s01a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_20/bd_0a27_sarn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_21/bd_0a27_srn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_25/bd_0a27_s02a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_26/bd_0a27_sarn_2_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_27/bd_0a27_srn_2_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_28/bd_0a27_sawn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_29/bd_0a27_swn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_30/bd_0a27_sbn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_31/bd_0a27_m00s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_32/bd_0a27_m00arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_33/bd_0a27_m00rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_34/bd_0a27_m00awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_35/bd_0a27_m00wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_36/bd_0a27_m00bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_38/bd_0a27_m01s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_39/bd_0a27_m01arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_40/bd_0a27_m01rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_41/bd_0a27_m01awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_42/bd_0a27_m01wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_43/bd_0a27_m01bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_45/bd_0a27_m02s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_46/bd_0a27_m02arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_47/bd_0a27_m02rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_48/bd_0a27_m02awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_49/bd_0a27_m02wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_50/bd_0a27_m02bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BAI1_4LED_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.srcs/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/BAI1_4LED_axi_smc_0.xci
# IP: The module: 'BAI1_4LED_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/bd_0a27.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_0/bd_0a27_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_2/bd_0a27_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_3/bd_0a27_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_4/bd_0a27_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_5/bd_0a27_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_6/bd_0a27_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_7/bd_0a27_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_8/bd_0a27_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_9/bd_0a27_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_10/bd_0a27_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_11/bd_0a27_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_12/bd_0a27_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_13/bd_0a27_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_14/bd_0a27_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_15/bd_0a27_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_16/bd_0a27_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_17/bd_0a27_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_18/bd_0a27_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_19/bd_0a27_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_20/bd_0a27_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_21/bd_0a27_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_22/bd_0a27_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_23/bd_0a27_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_24/bd_0a27_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_25/bd_0a27_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_26/bd_0a27_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_27/bd_0a27_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_28/bd_0a27_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_29/bd_0a27_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_30/bd_0a27_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_31/bd_0a27_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_32/bd_0a27_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_33/bd_0a27_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_34/bd_0a27_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_35/bd_0a27_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_36/bd_0a27_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_37/bd_0a27_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_38/bd_0a27_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_39/bd_0a27_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_40/bd_0a27_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_41/bd_0a27_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_42/bd_0a27_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_43/bd_0a27_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_44/bd_0a27_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_45/bd_0a27_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_46/bd_0a27_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_47/bd_0a27_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_48/bd_0a27_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_49/bd_0a27_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_50/bd_0a27_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_51/bd_0a27_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_1/bd_0a27_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_2/bd_0a27_arsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_3/bd_0a27_rsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_4/bd_0a27_awsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_5/bd_0a27_wsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_6/bd_0a27_bsw_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_10/bd_0a27_s00a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_11/bd_0a27_sarn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_12/bd_0a27_srn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_13/bd_0a27_sawn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_14/bd_0a27_swn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_15/bd_0a27_sbn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_19/bd_0a27_s01a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_20/bd_0a27_sarn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_21/bd_0a27_srn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_25/bd_0a27_s02a2s_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_26/bd_0a27_sarn_2_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_27/bd_0a27_srn_2_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_28/bd_0a27_sawn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_29/bd_0a27_swn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_30/bd_0a27_sbn_1_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_31/bd_0a27_m00s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_32/bd_0a27_m00arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_33/bd_0a27_m00rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_34/bd_0a27_m00awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_35/bd_0a27_m00wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_36/bd_0a27_m00bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_38/bd_0a27_m01s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_39/bd_0a27_m01arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_40/bd_0a27_m01rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_41/bd_0a27_m01awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_42/bd_0a27_m01wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_43/bd_0a27_m01bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_45/bd_0a27_m02s2a_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_46/bd_0a27_m02arn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_47/bd_0a27_m02rn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_48/bd_0a27_m02awn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_49/bd_0a27_m02wn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/bd_0/ip/ip_50/bd_0a27_m02bn_0_ooc.xdc

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BAI1_4LED_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
