# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/CODE/FPGA/BTTH/Bai6/Bai6.runs/synth_1/Bai6_4sw_4led_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CODE/FPGA/BTTH/Bai6/Bai6.cache/wt [current_project]
set_property parent.project_path D:/CODE/FPGA/BTTH/Bai6/Bai6.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/daoph/AppData/Roaming/Xilinx/Vivado/2022.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo d:/CODE/FPGA/BTTH/Bai6/Bai6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/hdl/Bai6_4sw_4led_wrapper.vhd
add_files D:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/sources_1/bd/Bai6_4sw_4led/Bai6_4sw_4led.bd
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mig_7series_0_0/Bai6_4sw_4led_mig_7series_0_0/user_design/constraints/Bai6_4sw_4led_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mig_7series_0_0/Bai6_4sw_4led_mig_7series_0_0/user_design/constraints/Bai6_4sw_4led_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mig_7series_0_0/Bai6_4sw_4led_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_clk_wiz_0_0/Bai6_4sw_4led_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_clk_wiz_0_0/Bai6_4sw_4led_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_clk_wiz_0_0/Bai6_4sw_4led_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_microblaze_0_0/Bai6_4sw_4led_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_microblaze_0_0/Bai6_4sw_4led_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_microblaze_0_0/Bai6_4sw_4led_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_dlmb_v10_0/Bai6_4sw_4led_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_ilmb_v10_0/Bai6_4sw_4led_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_dlmb_bram_if_cntlr_0/Bai6_4sw_4led_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_ilmb_bram_if_cntlr_0/Bai6_4sw_4led_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mdm_1_0/Bai6_4sw_4led_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mdm_1_0/Bai6_4sw_4led_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_rst_mig_7series_0_83M_0/Bai6_4sw_4led_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_rst_mig_7series_0_83M_0/Bai6_4sw_4led_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_rst_mig_7series_0_83M_0/Bai6_4sw_4led_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_1/bd_9734_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_1/bd_9734_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_2/bd_9734_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_3/bd_9734_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_4/bd_9734_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_5/bd_9734_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_6/bd_9734_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_10/bd_9734_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_11/bd_9734_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_12/bd_9734_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_13/bd_9734_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_14/bd_9734_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_15/bd_9734_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_19/bd_9734_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_20/bd_9734_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_21/bd_9734_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_25/bd_9734_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_26/bd_9734_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_27/bd_9734_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_28/bd_9734_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_29/bd_9734_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_30/bd_9734_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_31/bd_9734_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_32/bd_9734_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_33/bd_9734_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_34/bd_9734_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_35/bd_9734_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_36/bd_9734_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_38/bd_9734_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_39/bd_9734_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_40/bd_9734_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_41/bd_9734_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_42/bd_9734_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_43/bd_9734_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_45/bd_9734_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_46/bd_9734_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_47/bd_9734_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_48/bd_9734_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_49/bd_9734_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_50/bd_9734_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_52/bd_9734_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_53/bd_9734_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_54/bd_9734_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_55/bd_9734_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_56/bd_9734_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/bd_0/ip/ip_57/bd_9734_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_uartlite_0_0/Bai6_4sw_4led_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_uartlite_0_0/Bai6_4sw_4led_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_uartlite_0_0/Bai6_4sw_4led_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_0/Bai6_4sw_4led_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_0/Bai6_4sw_4led_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_0/Bai6_4sw_4led_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_1/Bai6_4sw_4led_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_1/Bai6_4sw_4led_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_1/Bai6_4sw_4led_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/Bai6_4sw_4led_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_microblaze_0_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/constrs_1/new/4SW4LEDdon.xdc
set_property used_in_implementation false [get_files D:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/constrs_1/new/4SW4LEDdon.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/utils_1/imports/synth_1/Bai6_4sw_4led_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Bai6_4sw_4led_wrapper -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Bai6_4sw_4led_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Bai6_4sw_4led_wrapper_utilization_synth.rpt -pb Bai6_4sw_4led_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
