# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/4SW4LEDdon.xdc

# Block Designs: bd/Bai6_4sw_4led/Bai6_4sw_4led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led || ORIG_REF_NAME==Bai6_4sw_4led} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mig_7series_0_0/Bai6_4sw_4led_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_mig_7series_0_0 || ORIG_REF_NAME==Bai6_4sw_4led_mig_7series_0_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_clk_wiz_0_0/Bai6_4sw_4led_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_clk_wiz_0_0 || ORIG_REF_NAME==Bai6_4sw_4led_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_microblaze_0_0/Bai6_4sw_4led_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_microblaze_0_0 || ORIG_REF_NAME==Bai6_4sw_4led_microblaze_0_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_dlmb_v10_0/Bai6_4sw_4led_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_dlmb_v10_0 || ORIG_REF_NAME==Bai6_4sw_4led_dlmb_v10_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_ilmb_v10_0/Bai6_4sw_4led_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_ilmb_v10_0 || ORIG_REF_NAME==Bai6_4sw_4led_ilmb_v10_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_dlmb_bram_if_cntlr_0/Bai6_4sw_4led_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Bai6_4sw_4led_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_ilmb_bram_if_cntlr_0/Bai6_4sw_4led_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Bai6_4sw_4led_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_lmb_bram_0 || ORIG_REF_NAME==Bai6_4sw_4led_lmb_bram_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_mdm_1_0/Bai6_4sw_4led_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_mdm_1_0 || ORIG_REF_NAME==Bai6_4sw_4led_mdm_1_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_rst_mig_7series_0_83M_0/Bai6_4sw_4led_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Bai6_4sw_4led_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_smc_0/Bai6_4sw_4led_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_axi_smc_0 || ORIG_REF_NAME==Bai6_4sw_4led_axi_smc_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_uartlite_0_0/Bai6_4sw_4led_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_axi_uartlite_0_0 || ORIG_REF_NAME==Bai6_4sw_4led_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_0/Bai6_4sw_4led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_axi_gpio_0_0 || ORIG_REF_NAME==Bai6_4sw_4led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_axi_gpio_0_1/Bai6_4sw_4led_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai6_4sw_4led_axi_gpio_0_1 || ORIG_REF_NAME==Bai6_4sw_4led_axi_gpio_0_1} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/Bai6_4sw_4led_ooc.xdc
