# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0.xci
# IP: The module: 'Bai6_4sw_4led_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bai6_4sw_4led_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai6/Bai6.srcs/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0.xci
# IP: The module: 'Bai6_4sw_4led_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai6/Bai6.gen/sources_1/bd/Bai6_4sw_4led/ip/Bai6_4sw_4led_lmb_bram_0/Bai6_4sw_4led_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bai6_4sw_4led_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
