# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bai11/bai11.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11 || ORIG_REF_NAME==bai11} -quiet] -quiet

# IP: bd/bai11/ip/bai11_mig_7series_0_0_1/bai11_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_mig_7series_0_0 || ORIG_REF_NAME==bai11_mig_7series_0_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_clk_wiz_0_0/bai11_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_clk_wiz_0_0 || ORIG_REF_NAME==bai11_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_microblaze_0_0/bai11_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_microblaze_0_0 || ORIG_REF_NAME==bai11_microblaze_0_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_dlmb_v10_0/bai11_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_dlmb_v10_0 || ORIG_REF_NAME==bai11_dlmb_v10_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_ilmb_v10_0/bai11_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_ilmb_v10_0 || ORIG_REF_NAME==bai11_ilmb_v10_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_dlmb_bram_if_cntlr_0/bai11_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bai11_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_ilmb_bram_if_cntlr_0/bai11_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bai11_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_lmb_bram_0/bai11_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_lmb_bram_0 || ORIG_REF_NAME==bai11_lmb_bram_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_mdm_1_0/bai11_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_mdm_1_0 || ORIG_REF_NAME==bai11_mdm_1_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_rst_mig_7series_0_83M_0/bai11_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==bai11_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_axi_smc_0/bai11_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_axi_smc_0 || ORIG_REF_NAME==bai11_axi_smc_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_axi_uartlite_0_0/bai11_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_axi_uartlite_0_0 || ORIG_REF_NAME==bai11_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bai11/ip/bai11_axi_gpio_0_0/bai11_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bai11_axi_gpio_0_0 || ORIG_REF_NAME==bai11_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai11/Bai11.gen/sources_1/bd/bai11/bai11_ooc.xdc
