# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai10/Bai10.srcs/sources_1/bd/Cau_10/ip/Cau_10_dlmb_v10_0/Cau_10_dlmb_v10_0.xci
# IP: The module: 'Cau_10_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai10/Bai10.gen/sources_1/bd/Cau_10/ip/Cau_10_dlmb_v10_0/Cau_10_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cau_10_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai10/Bai10.srcs/sources_1/bd/Cau_10/ip/Cau_10_dlmb_v10_0/Cau_10_dlmb_v10_0.xci
# IP: The module: 'Cau_10_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai10/Bai10.gen/sources_1/bd/Cau_10/ip/Cau_10_dlmb_v10_0/Cau_10_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cau_10_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
