set_property SRC_FILE_INFO {cfile:D:/CODE/FPGA/BUTTON_LED_1/BUTTON_LED_1.srcs/constrs_1/new/chan_gpio.xdc rfile:../../../BUTTON_LED_1.srcs/constrs_1/new/chan_gpio.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports {button_pin_tri_i[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports {led_pin_tri_o[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {led_pin_tri_o[0]}]
