# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai13/Bai13.srcs/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0.xci
# IP: The module: 'bai13_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai13/Bai13.srcs/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0.xci
# IP: The module: 'bai13_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai13/Bai13.gen/sources_1/bd/bai13/ip/bai13_axi_gpio_0_0/bai13_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bai13_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
