# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/chan_cang.xdc

# Block Designs: bd/Bai12/Bai12.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12 || ORIG_REF_NAME==Bai12} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_clk_wiz_0_0/Bai12_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_clk_wiz_0_0 || ORIG_REF_NAME==Bai12_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_mig_7series_0_0_1/Bai12_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_mig_7series_0_0 || ORIG_REF_NAME==Bai12_mig_7series_0_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_microblaze_0_0/Bai12_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_microblaze_0_0 || ORIG_REF_NAME==Bai12_microblaze_0_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_dlmb_v10_0/Bai12_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_dlmb_v10_0 || ORIG_REF_NAME==Bai12_dlmb_v10_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_ilmb_v10_0/Bai12_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_ilmb_v10_0 || ORIG_REF_NAME==Bai12_ilmb_v10_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_dlmb_bram_if_cntlr_0/Bai12_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Bai12_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_ilmb_bram_if_cntlr_0/Bai12_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Bai12_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_lmb_bram_0/Bai12_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_lmb_bram_0 || ORIG_REF_NAME==Bai12_lmb_bram_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_mdm_1_0/Bai12_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_mdm_1_0 || ORIG_REF_NAME==Bai12_mdm_1_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_rst_mig_7series_0_83M_0/Bai12_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Bai12_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_axi_smc_0/Bai12_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_axi_smc_0 || ORIG_REF_NAME==Bai12_axi_smc_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_axi_uartlite_0_0/Bai12_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_axi_uartlite_0_0 || ORIG_REF_NAME==Bai12_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Bai12/ip/Bai12_axi_gpio_0_0/Bai12_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Bai12_axi_gpio_0_0 || ORIG_REF_NAME==Bai12_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/bai12/bai12.gen/sources_1/bd/Bai12/Bai12_ooc.xdc
