# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sw4/sw4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4 || ORIG_REF_NAME==sw4} -quiet] -quiet

# IP: bd/sw4/ip/sw4_mig_7series_0_0/sw4_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_mig_7series_0_0 || ORIG_REF_NAME==sw4_mig_7series_0_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_clk_wiz_0_0/sw4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_clk_wiz_0_0 || ORIG_REF_NAME==sw4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_microblaze_0_0/sw4_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_microblaze_0_0 || ORIG_REF_NAME==sw4_microblaze_0_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_dlmb_v10_0/sw4_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_dlmb_v10_0 || ORIG_REF_NAME==sw4_dlmb_v10_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_ilmb_v10_0/sw4_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_ilmb_v10_0 || ORIG_REF_NAME==sw4_ilmb_v10_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_dlmb_bram_if_cntlr_0/sw4_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sw4_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_ilmb_bram_if_cntlr_0/sw4_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sw4_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_lmb_bram_0/sw4_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_lmb_bram_0 || ORIG_REF_NAME==sw4_lmb_bram_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_mdm_1_0/sw4_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_mdm_1_0 || ORIG_REF_NAME==sw4_mdm_1_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_rst_mig_7series_0_83M_0/sw4_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==sw4_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_axi_smc_0/sw4_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_axi_smc_0 || ORIG_REF_NAME==sw4_axi_smc_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_axi_uartlite_0_0/sw4_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_axi_uartlite_0_0 || ORIG_REF_NAME==sw4_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/sw4/ip/sw4_axi_gpio_0_0/sw4_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sw4_axi_gpio_0_0 || ORIG_REF_NAME==sw4_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai/Bai.gen/sources_1/bd/sw4/sw4_ooc.xdc
