# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai9/Bai9.srcs/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0.xci
# IP: The module: 'BTN_LED_don_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai9/Bai9.srcs/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0.xci
# IP: The module: 'BTN_LED_don_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BTN_LED_don_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
