# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rgbx4_swx4.xdc

# Block Designs: bd/Cau_10/Cau_10.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10 || ORIG_REF_NAME==Cau_10} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_mig_7series_0_0/Cau_10_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_mig_7series_0_0 || ORIG_REF_NAME==Cau_10_mig_7series_0_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_clk_wiz_0_0/Cau_10_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_clk_wiz_0_0 || ORIG_REF_NAME==Cau_10_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_microblaze_0_0/Cau_10_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_microblaze_0_0 || ORIG_REF_NAME==Cau_10_microblaze_0_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_dlmb_v10_0/Cau_10_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_dlmb_v10_0 || ORIG_REF_NAME==Cau_10_dlmb_v10_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_ilmb_v10_0/Cau_10_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_ilmb_v10_0 || ORIG_REF_NAME==Cau_10_ilmb_v10_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_dlmb_bram_if_cntlr_0/Cau_10_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Cau_10_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_ilmb_bram_if_cntlr_0/Cau_10_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Cau_10_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_lmb_bram_0/Cau_10_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_lmb_bram_0 || ORIG_REF_NAME==Cau_10_lmb_bram_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_mdm_1_0/Cau_10_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_mdm_1_0 || ORIG_REF_NAME==Cau_10_mdm_1_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_rst_mig_7series_0_83M_0/Cau_10_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Cau_10_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_axi_smc_0/Cau_10_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_axi_smc_0 || ORIG_REF_NAME==Cau_10_axi_smc_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_axi_uartlite_0_0/Cau_10_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_axi_uartlite_0_0 || ORIG_REF_NAME==Cau_10_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_axi_gpio_0_0/Cau_10_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_axi_gpio_0_0 || ORIG_REF_NAME==Cau_10_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Cau_10/ip/Cau_10_RGB_0/Cau_10_RGB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Cau_10_RGB_0 || ORIG_REF_NAME==Cau_10_RGB_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai10/Bai10.gen/sources_1/bd/Cau_10/Cau_10_ooc.xdc
