# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/3SW_2LED/3SW_2LED.srcs/sources_1/bd/btn_led/ip/btn_led_ilmb_bram_if_cntlr_0/btn_led_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'btn_led_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/3SW_2LED/3SW_2LED.gen/sources_1/bd/btn_led/ip/btn_led_ilmb_bram_if_cntlr_0/btn_led_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'btn_led_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/3SW_2LED/3SW_2LED.srcs/sources_1/bd/btn_led/ip/btn_led_ilmb_bram_if_cntlr_0/btn_led_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'btn_led_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/3SW_2LED/3SW_2LED.gen/sources_1/bd/btn_led/ip/btn_led_ilmb_bram_if_cntlr_0/btn_led_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'btn_led_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
