# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/BTN_LED_DON.xdc

# Block Designs: bd/BTN_LED_don/BTN_LED_don.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don || ORIG_REF_NAME==BTN_LED_don} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_mig_7series_0_0/BTN_LED_don_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_mig_7series_0_0 || ORIG_REF_NAME==BTN_LED_don_mig_7series_0_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_clk_wiz_0_0/BTN_LED_don_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_clk_wiz_0_0 || ORIG_REF_NAME==BTN_LED_don_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_microblaze_0_0/BTN_LED_don_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_microblaze_0_0 || ORIG_REF_NAME==BTN_LED_don_microblaze_0_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_dlmb_v10_0/BTN_LED_don_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_dlmb_v10_0 || ORIG_REF_NAME==BTN_LED_don_dlmb_v10_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_ilmb_v10_0/BTN_LED_don_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_ilmb_v10_0 || ORIG_REF_NAME==BTN_LED_don_ilmb_v10_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_dlmb_bram_if_cntlr_0/BTN_LED_don_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BTN_LED_don_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_ilmb_bram_if_cntlr_0/BTN_LED_don_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BTN_LED_don_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_lmb_bram_0/BTN_LED_don_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_lmb_bram_0 || ORIG_REF_NAME==BTN_LED_don_lmb_bram_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_mdm_1_0/BTN_LED_don_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_mdm_1_0 || ORIG_REF_NAME==BTN_LED_don_mdm_1_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_rst_mig_7series_0_83M_0/BTN_LED_don_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==BTN_LED_don_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_axi_smc_0/BTN_LED_don_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_axi_smc_0 || ORIG_REF_NAME==BTN_LED_don_axi_smc_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_axi_uartlite_0_0/BTN_LED_don_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_axi_uartlite_0_0 || ORIG_REF_NAME==BTN_LED_don_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_axi_gpio_0_1/BTN_LED_don_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_axi_gpio_0_1 || ORIG_REF_NAME==BTN_LED_don_axi_gpio_0_1} -quiet] -quiet

# IP: bd/BTN_LED_don/ip/BTN_LED_don_axi_gpio_0_2/BTN_LED_don_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BTN_LED_don_axi_gpio_0_2 || ORIG_REF_NAME==BTN_LED_don_axi_gpio_0_2} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai9/Bai9.gen/sources_1/bd/BTN_LED_don/BTN_LED_don_ooc.xdc
