# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PIN.xdc

# Block Designs: bd/rgb_design/rgb_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design || ORIG_REF_NAME==rgb_design} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_clk_wiz_0_0/rgb_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_clk_wiz_0_0 || ORIG_REF_NAME==rgb_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_mig_7series_0_0/rgb_design_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_mig_7series_0_0 || ORIG_REF_NAME==rgb_design_mig_7series_0_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_microblaze_0_0/rgb_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_microblaze_0_0 || ORIG_REF_NAME==rgb_design_microblaze_0_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_dlmb_v10_0/rgb_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_dlmb_v10_0 || ORIG_REF_NAME==rgb_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_ilmb_v10_0/rgb_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_ilmb_v10_0 || ORIG_REF_NAME==rgb_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_dlmb_bram_if_cntlr_0/rgb_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==rgb_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_ilmb_bram_if_cntlr_0/rgb_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==rgb_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_lmb_bram_0/rgb_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_lmb_bram_0 || ORIG_REF_NAME==rgb_design_lmb_bram_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_mdm_1_0/rgb_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_mdm_1_0 || ORIG_REF_NAME==rgb_design_mdm_1_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_rst_mig_7series_0_83M_0/rgb_design_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==rgb_design_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_axi_smc_0/rgb_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_axi_smc_0 || ORIG_REF_NAME==rgb_design_axi_smc_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_axi_uartlite_0_0 || ORIG_REF_NAME==rgb_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/rgb_design/ip/rgb_design_axi_gpio_0_0/rgb_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb_design_axi_gpio_0_0 || ORIG_REF_NAME==rgb_design_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/rgb_design_ooc.xdc
