set_property PACKAGE_PIN G6 [get_ports {led_rgb_tri_o[0]}]
set_property PACKAGE_PIN F6 [get_ports {led_rgb_tri_o[1]}]
set_property PACKAGE_PIN E1 [get_ports {led_rgb_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb_tri_o[0]}]
