# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BAI1_4LED/BAI1_4LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED || ORIG_REF_NAME==BAI1_4LED} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_mig_7series_0_0_2/BAI1_4LED_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_mig_7series_0_0 || ORIG_REF_NAME==BAI1_4LED_mig_7series_0_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_clk_wiz_0_0/BAI1_4LED_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_clk_wiz_0_0 || ORIG_REF_NAME==BAI1_4LED_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_microblaze_0_0/BAI1_4LED_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_microblaze_0_0 || ORIG_REF_NAME==BAI1_4LED_microblaze_0_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_dlmb_v10_0/BAI1_4LED_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_dlmb_v10_0 || ORIG_REF_NAME==BAI1_4LED_dlmb_v10_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_ilmb_v10_0/BAI1_4LED_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_ilmb_v10_0 || ORIG_REF_NAME==BAI1_4LED_ilmb_v10_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_dlmb_bram_if_cntlr_0/BAI1_4LED_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BAI1_4LED_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_ilmb_bram_if_cntlr_0/BAI1_4LED_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BAI1_4LED_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_lmb_bram_0/BAI1_4LED_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_lmb_bram_0 || ORIG_REF_NAME==BAI1_4LED_lmb_bram_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_mdm_1_0/BAI1_4LED_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_mdm_1_0 || ORIG_REF_NAME==BAI1_4LED_mdm_1_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_rst_mig_7series_0_83M_0/BAI1_4LED_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==BAI1_4LED_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_axi_smc_0/BAI1_4LED_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_axi_smc_0 || ORIG_REF_NAME==BAI1_4LED_axi_smc_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_axi_uartlite_0_0/BAI1_4LED_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_axi_uartlite_0_0 || ORIG_REF_NAME==BAI1_4LED_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BAI1_4LED/ip/BAI1_4LED_axi_gpio_0_0/BAI1_4LED_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI1_4LED_axi_gpio_0_0 || ORIG_REF_NAME==BAI1_4LED_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai1/Bai1.gen/sources_1/bd/BAI1_4LED/BAI1_4LED_ooc.xdc
