# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/BTTH/Bai4/Bai4.srcs/sources_1/bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_bram_if_cntlr_0/BAI4_4RGB_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'BAI4_4RGB_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai4/Bai4.gen/sources_1/bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_bram_if_cntlr_0/BAI4_4RGB_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BAI4_4RGB_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/BTTH/Bai4/Bai4.srcs/sources_1/bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_bram_if_cntlr_0/BAI4_4RGB_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'BAI4_4RGB_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/BTTH/Bai4/Bai4.gen/sources_1/bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_bram_if_cntlr_0/BAI4_4RGB_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BAI4_4RGB_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
