# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODE/FPGA/RGB/RGB.srcs/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0.xci
# IP: The module: 'rgb_design_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CODE/FPGA/RGB/RGB.srcs/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0.xci
# IP: The module: 'rgb_design_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/CODE/FPGA/RGB/RGB.gen/sources_1/bd/rgb_design/ip/rgb_design_axi_uartlite_0_0/rgb_design_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb_design_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
