# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/4_RGB.xdc

# Block Designs: bd/BAI4_4RGB/BAI4_4RGB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB || ORIG_REF_NAME==BAI4_4RGB} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_clk_wiz_0_0/BAI4_4RGB_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_clk_wiz_0_0 || ORIG_REF_NAME==BAI4_4RGB_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_mig_7series_0_0_1/BAI4_4RGB_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_mig_7series_0_0 || ORIG_REF_NAME==BAI4_4RGB_mig_7series_0_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_microblaze_0_0/BAI4_4RGB_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_microblaze_0_0 || ORIG_REF_NAME==BAI4_4RGB_microblaze_0_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_v10_0/BAI4_4RGB_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_dlmb_v10_0 || ORIG_REF_NAME==BAI4_4RGB_dlmb_v10_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_ilmb_v10_0/BAI4_4RGB_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_ilmb_v10_0 || ORIG_REF_NAME==BAI4_4RGB_ilmb_v10_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_dlmb_bram_if_cntlr_0/BAI4_4RGB_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BAI4_4RGB_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_ilmb_bram_if_cntlr_0/BAI4_4RGB_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BAI4_4RGB_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_lmb_bram_0/BAI4_4RGB_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_lmb_bram_0 || ORIG_REF_NAME==BAI4_4RGB_lmb_bram_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_mdm_1_0/BAI4_4RGB_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_mdm_1_0 || ORIG_REF_NAME==BAI4_4RGB_mdm_1_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_rst_mig_7series_0_83M_0/BAI4_4RGB_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==BAI4_4RGB_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_axi_smc_0/BAI4_4RGB_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_axi_smc_0 || ORIG_REF_NAME==BAI4_4RGB_axi_smc_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_axi_uartlite_0_0/BAI4_4RGB_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_axi_uartlite_0_0 || ORIG_REF_NAME==BAI4_4RGB_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BAI4_4RGB/ip/BAI4_4RGB_axi_gpio_0_0/BAI4_4RGB_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BAI4_4RGB_axi_gpio_0_0 || ORIG_REF_NAME==BAI4_4RGB_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/CODE/FPGA/BTTH/Bai4/Bai4.gen/sources_1/bd/BAI4_4RGB/BAI4_4RGB_ooc.xdc
